import { defaults } from "./defaults.js";
import { db, auth, collection, getDocs, doc, getDoc, setDoc, updateDoc, deleteDoc, onSnapshot, query, orderBy, signInWithEmailAndPassword, signOut, onAuthStateChanged } from "./firebase.js";

const $ = (selector) => document.querySelector(selector);
const state = { orders: [], plans: [], charts: {}, unsubscribeOrders: null, unsubscribeVisits: null, orderIdsSeen: new Set(), ordersLoadedOnce: false, pageSize: 10, visibleOrders: 10, signedOutByUser: false };
const escapeHtml = (value) => String(value ?? "").replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[character]));
const setStatus = (message, bad = false) => { const node = $("#app:not([hidden]) #admin-status, #login:not([hidden]) #login-status"); if (node) { node.textContent = message; node.dataset.bad = String(bad); } };
const setLoading = (selector, loading) => { const node = $(selector); if (node) node.hidden = !loading; };
const getDate = (value) => { if (!value) return null; if (typeof value.toDate === "function") return value.toDate(); if (value.seconds) return new Date(value.seconds * 1000); const date = new Date(value); return Number.isNaN(date.getTime()) ? null : date; };
const formatDate = (value) => { const date = getDate(value); return date ? new Intl.DateTimeFormat("pt-PT", { dateStyle: "medium", timeStyle: "short" }).format(date) : "Data não disponível"; };
const showLogin = (message = "") => { $("#app").hidden = true; $("#login").hidden = false; $("#admin-email").value = ""; $("#admin-password").value = ""; $("#login-status").textContent = message; };
const showApp = () => { $("#login").hidden = true; $("#app").hidden = false; };

function cleanupListeners() { if (state.unsubscribeOrders) { state.unsubscribeOrders(); state.unsubscribeOrders = null; } if (state.unsubscribeVisits) { state.unsubscribeVisits(); state.unsubscribeVisits = null; } state.orders = []; state.orderIdsSeen = new Set(); state.ordersLoadedOnce = false; destroyCharts(); }
function destroyCharts() { Object.values(state.charts).forEach((chart) => chart?.destroy()); state.charts = {}; }
function updateSummary(orders) {
  const now = new Date();
  const thisMonth = orders.filter((order) => { const date = getDate(order.criadoEm); return date && date.getFullYear() === now.getFullYear() && date.getMonth() === now.getMonth(); }).length;
  const byPlan = orders.reduce((result, order) => { const plan = order.plano || "Ainda não sei"; result[plan] = (result[plan] || 0) + 1; return result; }, {});
  $("#summary-total").textContent = String(orders.length); $("#summary-new").textContent = String(orders.filter((order) => order.estado === "novo").length); $("#summary-month").textContent = String(thisMonth);
  const planEntries = Object.entries(byPlan).sort((a, b) => b[1] - a[1]); $("#summary-plans").innerHTML = planEntries.length ? planEntries.map(([plan, count]) => `<span>${escapeHtml(`Plano ${plan}: ${count}`)}</span>`).join("") : "<span>Sem pedidos</span>";
}
function chartColors() { const styles = getComputedStyle(document.documentElement); return { blue: styles.getPropertyValue("--blue").trim() || "#2f5dff", mint: styles.getPropertyValue("--mint").trim() || "#2bc5a6", text: styles.getPropertyValue("--text").trim() || "#1c1c1e", line: styles.getPropertyValue("--line").trim() || "#e5e5e0" }; }
function monthBuckets(months = 12) { const now = new Date(); return Array.from({ length: months }, (_, index) => { const date = new Date(now.getFullYear(), now.getMonth() - months + index + 1, 1); return { key: `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`, label: new Intl.DateTimeFormat("pt-PT", { month: "short", year: "2-digit" }).format(date) }; }); }
function countBy(items, getKey) { return items.reduce((result, item) => { const key = getKey(item) || "Não indicado"; result[key] = (result[key] || 0) + 1; return result; }, {}); }
function renderCharts() {
  if (!window.Chart) return;
  const colors = chartColors(); const months = monthBuckets(); const labels = months.map((month) => month.label); const keys = new Set(months.map((month) => month.key));
  destroyCharts();
  const base = { responsive: true, maintainAspectRatio: false, plugins: { legend: { labels: { color: colors.text } } }, scales: { x: { ticks: { color: colors.text }, grid: { color: colors.line } }, y: { beginAtZero: true, ticks: { precision: 0, color: colors.text }, grid: { color: colors.line } } } };
  const monthCounts = months.reduce((result, month) => { result[month.key] = 0; return result; }, {}); state.orders.forEach((order) => { const date = getDate(order.criadoEm); if (date) { const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`; if (keys.has(key)) monthCounts[key] += 1; } });
  state.charts.time = new Chart($("#orders-time-chart"), { type: "line", data: { labels, datasets: [{ label: "Pedidos", data: months.map((month) => monthCounts[month.key]), borderColor: colors.blue, backgroundColor: "rgba(47,93,255,.14)", fill: true, tension: .3 }] }, options: base });
  const statuses = ["novo", "contactado", "fechado", "perdido"]; const statusCounts = countBy(state.orders, (order) => statuses.includes(order.estado) ? order.estado : "novo");
  state.charts.status = new Chart($("#orders-status-chart"), { type: "doughnut", data: { labels: statuses.map((status) => status[0].toUpperCase() + status.slice(1)), datasets: [{ data: statuses.map((status) => statusCounts[status] || 0), backgroundColor: [colors.blue, colors.mint, "#7b61ff", "#c6c6c0"] }] }, options: { ...base, scales: {} } });
  const plans = countBy(state.orders, (order) => order.plano); state.charts.plan = new Chart($("#orders-plan-chart"), { type: "bar", data: { labels: Object.keys(plans), datasets: [{ label: "Pedidos", data: Object.values(plans), backgroundColor: colors.mint }] }, options: base });
  const businesses = countBy(state.orders, (order) => order.tipoNegocio); state.charts.business = new Chart($("#orders-business-chart"), { type: "bar", data: { labels: Object.keys(businesses), datasets: [{ label: "Pedidos", data: Object.values(businesses), backgroundColor: colors.blue }] }, options: base });
  const prices = state.plans.reduce((result, plan) => { result[plan.id] = Number(plan.preco) || 0; result[plan.nome] = Number(plan.preco) || 0; return result; }, {}); const revenue = months.reduce((result, month) => { result[month.key] = 0; return result; }, {});
  state.orders.filter((order) => order.estado === "fechado").forEach((order) => { const date = getDate(order.criadoEm); if (!date) return; const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`; if (keys.has(key)) revenue[key] += prices[order.plano] || 0; });
  state.charts.revenue = new Chart($("#revenue-chart"), { type: "bar", data: { labels, datasets: [{ label: "Receita estimada (€)", data: months.map((month) => revenue[month.key]), backgroundColor: colors.blue }] }, options: { ...base, scales: { ...base.scales, y: { ...base.scales.y, ticks: { ...base.scales.y.ticks, callback: (value) => `${value}€` } } } } });
}
function filteredOrders() { const search = $("#order-search").value.trim().toLocaleLowerCase("pt-PT"); const status = $("#order-status-filter").value; return state.orders.filter((order) => (!search || `${order.nome || ""} ${order.email || ""}`.toLocaleLowerCase("pt-PT").includes(search)) && (status === "todos" || order.estado === status)); }
function renderOrders() {
  const root = $("#orders"); const more = $("#orders-more"); const orders = filteredOrders(); const visible = orders.slice(0, state.visibleOrders);
  root.innerHTML = visible.length ? visible.map((order) => { const id = escapeHtml(order.id); const status = ["novo", "contactado", "fechado", "perdido"].includes(order.estado) ? order.estado : "novo"; return `<article class="card admin-row ${status === "novo" ? "is-new" : ""}" data-order-id="${id}"><div class="admin-row-head"><div><strong>${escapeHtml(order.nome || "Sem nome")}</strong><div class="admin-date">${escapeHtml(formatDate(order.criadoEm))}</div></div>${status === "novo" ? '<span class="admin-badge">Novo</span>' : ""}</div><span>${escapeHtml(order.email)} · ${escapeHtml(order.telefone)} · ${escapeHtml(order.tipoNegocio)} · ${escapeHtml(order.plano)}</span><p>${escapeHtml(order.mensagem)}</p><div class="field"><label for="state-${id}">Estado</label><select id="state-${id}" data-state="${id}"><option value="novo" ${status === "novo" ? "selected" : ""}>Novo</option><option value="contactado" ${status === "contactado" ? "selected" : ""}>Contactado</option><option value="fechado" ${status === "fechado" ? "selected" : ""}>Fechado</option><option value="perdido" ${status === "perdido" ? "selected" : ""}>Perdido</option></select></div><div class="field"><label for="note-${id}">Nota interna</label><textarea id="note-${id}" data-note="${id}" placeholder="Nota interna">${escapeHtml(order.notaInterna)}</textarea></div><div class="admin-action-row"><button class="btn btn-small" type="button" data-save="${id}" aria-label="Guardar alterações do pedido de ${escapeHtml(order.nome || "sem nome")}">Guardar</button><button class="btn btn-secondary btn-small" type="button" data-delete="${id}" aria-label="Apagar pedido de ${escapeHtml(order.nome || "sem nome")}">Apagar</button></div></article>`; }).join("") : "<p>Ainda não existem pedidos para este filtro.</p>";
  more.hidden = orders.length <= state.visibleOrders; root.querySelectorAll("[data-save]").forEach((button) => button.addEventListener("click", saveOrder)); root.querySelectorAll("[data-delete]").forEach((button) => button.addEventListener("click", removeOrder));
}
async function saveOrder(event) { const row = event.currentTarget.closest("[data-order-id]"); const id = row.dataset.orderId; try { await updateDoc(doc(db, "pedidos", id), { estado: row.querySelector("[data-state]").value, notaInterna: row.querySelector("[data-note]").value }); setStatus("Pedido atualizado."); } catch (error) { setStatus("Não foi possível atualizar o pedido.", true); console.error(error); } }
async function removeOrder(event) { const id = event.currentTarget.closest("[data-order-id]").dataset.orderId; if (!confirm("Apagar este pedido?")) return; try { await deleteDoc(doc(db, "pedidos", id)); setStatus("Pedido apagado."); } catch (error) { setStatus("Não foi possível apagar o pedido.", true); console.error(error); } }
function loadOrders() { if (!db) { $("#orders-error").textContent = "Firebase não está configurado."; return; } cleanupListeners(); setLoading("#orders-loading", true); $("#orders-error").textContent = ""; const orderQuery = query(collection(db, "pedidos"), orderBy("criadoEm", "desc")); state.unsubscribeOrders = onSnapshot(orderQuery, (snapshot) => { const currentOrderIds = new Set(snapshot.docs.map((item) => item.id)); if (state.ordersLoadedOnce && window.Notification && Notification.permission === "granted") snapshot.docs.forEach((item) => { const order = item.data(); if (order.estado === "novo" && !state.orderIdsSeen.has(item.id)) new Notification("Novo pedido — NayWeb", { body: `${order.nome || "Sem nome"} · ${order.plano || ""}` }); }); state.orderIdsSeen = currentOrderIds; state.ordersLoadedOnce = true; state.orders = snapshot.docs.map((item) => ({ id: item.id, ...item.data() })).sort((a, b) => { const newOrder = Number(b.estado === "novo") - Number(a.estado === "novo"); return newOrder || ((getDate(b.criadoEm)?.getTime() || 0) - (getDate(a.criadoEm)?.getTime() || 0)); }); state.visibleOrders = state.pageSize; updateSummary(state.orders); renderOrders(); renderCharts(); setLoading("#orders-loading", false); }, (error) => { setLoading("#orders-loading", false); $("#orders-error").textContent = error.code === "permission-denied" ? "Sem permissões para ler pedidos. Confirma o documento admins/{UID} e as regras Firestore." : "Não foi possível carregar os pedidos."; console.error(error); }); }
function loadVisits() { if (!db) return; if (state.unsubscribeVisits) state.unsubscribeVisits(); $("#visits-error").textContent = ""; state.unsubscribeVisits = onSnapshot(doc(db, "estatisticas", "visitas"), (snapshot) => { $("#visits-total").textContent = String(snapshot.exists() ? snapshot.data().total || 0 : 0); }, (error) => { $("#visits-total").textContent = "—"; $("#visits-error").textContent = error.code === "permission-denied" ? "Sem permissões para ler as visitas. Publica as regras de firestore.rules na consola do Firebase." : "Não foi possível carregar as visitas."; console.error("loadVisits:", error.code, error.message); }); }
async function loadPlans() { if (!db) { $("#plans-error").textContent = "Firebase não está configurado."; return; } setLoading("#plans-loading", true); $("#plans-error").textContent = ""; try { const snapshot = await getDocs(collection(db, "planos")); state.plans = snapshot.docs.map((item) => ({ id: item.id, ...item.data() })); const root = $("#plans"); root.innerHTML = snapshot.docs.map((item) => { const plan = item.data(); const id = escapeHtml(item.id); return `<article class="card admin-row"><strong>${escapeHtml(plan.nome || item.id)}</strong><div class="field"><label for="price-${id}">Preço</label><input id="price-${id}" type="number" data-price="${id}" value="${escapeHtml(plan.preco || 0)}"></div><div class="field"><label for="setup-price-${id}">Preço de criação</label><input id="setup-price-${id}" type="number" step="0.01" data-setup-price="${id}" value="${escapeHtml(plan.precoCriacao || 0)}"></div><div class="field"><label for="description-${id}">Descrição</label><input id="description-${id}" data-description="${id}" value="${escapeHtml(plan.descricao)}"></div><button class="btn btn-small" type="button" data-plan-save="${id}" aria-label="Guardar plano ${escapeHtml(plan.nome || item.id)}">Guardar plano</button></article>`; }).join("") || "<p>Carrega os dados iniciais para começar.</p>"; root.querySelectorAll("[data-plan-save]").forEach((button) => button.addEventListener("click", savePlan)); renderCharts(); } catch (error) { $("#plans-error").textContent = error.code === "permission-denied" ? "Sem permissões para ler planos." : "Não foi possível carregar os planos."; console.error(error); } finally { setLoading("#plans-loading", false); } }
async function savePlan(event) { const row = event.currentTarget.closest(".admin-row"); const id = event.currentTarget.dataset.planSave; try { await updateDoc(doc(db, "planos", id), { preco: Number(row.querySelector("[data-price]").value), precoCriacao: Number(row.querySelector("[data-setup-price]").value), descricao: row.querySelector("[data-description]").value }); setStatus("Plano atualizado."); } catch (error) { setStatus("Não foi possível atualizar o plano.", true); console.error(error); } }
async function seed() { if (!db || !confirm("Carregar dados iniciais no Firestore?")) return; try { for (const plan of defaults.planos) await setDoc(doc(db, "planos", plan.id), plan); for (const item of defaults.exemplos) { const { id, ...data } = item; await setDoc(doc(db, "exemplos", id), data); } for (const [index, item] of defaults.faq.entries()) await setDoc(doc(db, "faq", `faq-${index + 1}`), item); await setDoc(doc(db, "configuracoes", "site"), defaults.configuracoes); setStatus("Dados iniciais carregados."); await loadPlans(); } catch (error) { setStatus("Não foi possível carregar os dados iniciais.", true); console.error(error); } }
async function checkAdmin(user) { if (!user || !db) return false; const admin = await getDoc(doc(db, "admins", user.uid)); return admin.exists(); }

$("#login-form").addEventListener("submit", async (event) => { event.preventDefault(); try { if (!auth) throw new Error("Firebase não está configurado."); await signInWithEmailAndPassword(auth, $("#admin-email").value, $("#admin-password").value); } catch (error) { setStatus(error.code === "auth/invalid-credential" ? "Email ou palavra-passe inválidos." : error.message, true); } });
$("#logout").addEventListener("click", async () => { state.signedOutByUser = true; cleanupListeners(); showLogin(); try { if (auth) await signOut(auth); } catch (error) { setStatus("Não foi possível terminar a sessão.", true); console.error(error); } });
$("#enable-notifications").addEventListener("click", async () => { if (!("Notification" in window)) { setStatus("As notificações não são suportadas neste browser.", true); return; } const permission = await Notification.requestPermission(); setStatus(permission === "granted" ? "Notificações ativadas." : "Notificações recusadas.", permission !== "granted"); });
$("#seed").addEventListener("click", seed); $("#order-search").addEventListener("input", () => { state.visibleOrders = state.pageSize; renderOrders(); }); $("#order-status-filter").addEventListener("change", () => { state.visibleOrders = state.pageSize; renderOrders(); }); $("#orders-more").addEventListener("click", () => { state.visibleOrders += state.pageSize; renderOrders(); }); document.querySelectorAll("[data-tab]").forEach((button) => button.addEventListener("click", () => { document.querySelectorAll(".admin-panel").forEach((panel) => panel.classList.toggle("is-active", panel.id === button.dataset.tab)); if (button.dataset.tab === "charts-panel") renderCharts(); }));

if (auth) onAuthStateChanged(auth, async (user) => { if (!user) { cleanupListeners(); if (!state.signedOutByUser) showLogin(); state.signedOutByUser = false; return; } try { if (await checkAdmin(user)) { showApp(); loadOrders(); await loadPlans(); loadVisits(); } else { await signOut(auth); showLogin("A tua conta não tem permissões de administrador."); } } catch (error) { await signOut(auth); showLogin("Não foi possível verificar as permissões de administrador."); console.error(error); } }); else showLogin("Configura o Firebase antes de entrar.");
